name: Linting

on:
  push:
    branches:
      - main
      - master
      - develop
  pull_request:
  schedule:
    - cron: "0 0 * * *"

env:
  DEFAULT_PYTHON: "3.11"

jobs:
  pre-commit:
    runs-on: "ubuntu-latest"
    name: Pre-commit and pytest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3.5.3

      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
        uses: actions/setup-python@v4.7.0
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}

      - name: Install Python modules
        run: |
          pip install --no-cache-dir -r requirements.txt
          # json files on syrupy are broken before 4.0.4, but pytest-homeassistant-custom-component for our current HA
          # version relies on 4.0.2
          pip install --no-deps syrupy==4.0.4

      - name: Run pre-commit on all files
        run: |
          pre-commit run --all-files --show-diff-on-failure --color=always

      - name: Run pytest
        run: |
          python -m pytest

  hacs:
    runs-on: "ubuntu-latest"
    name: HACS
    steps:
      - name: Check out the repository
        uses: "actions/checkout@v3.5.3"

      - name: HACS validation
        uses: "hacs/action@22.5.0"
        with:
          category: "integration"

  hassfest:
    runs-on: "ubuntu-latest"
    name: Hassfest
    steps:
      - name: Check out the repository
        uses: "actions/checkout@v3.5.3"

      - name: Hassfest validation
        uses: "home-assistant/actions/hassfest@master"
